// seed/06.variants.manual.full.ts
import { PrismaClient } from '@prisma/client';

/**
 * NHẬP TAY 100% — KHÔNG map, KHÔNG generate.
 * LƯU Ý: size_id đang để null để tránh lệch ID tự tăng giữa các máy/DB.
 * Sau khi có size_id thật trong DB của bạn, sửa tay từng dòng cho đúng.
 */

// ===== DANH SÁCH VARIANTS THỦ CÔNG =====
const variantsData = [
  // ====================== ADIDAS (brand_id: 1) ======================
  // 1) Adidas Adicolor Jacquard Jersey (Men) – tops: S/M/L
  {
    product_id: 1,
    size_id: 1,
    sku: 'ADI-AJJ-M-BLK-S',
    barcode: '10000000',
    base_price: 900000,
    quantity: 100,
    status: true,
    attribute: {
      'chất liệu': 'cotton jacquard',
      form: 'regular',
      màu: 'black',
      'phong cách': 'originals',
    },
  },
  {
    product_id: 1,
    size_id: 2,
    sku: 'ADI-AJJ-M-BLK-M',
    barcode: '10000001',
    base_price: 900000,
    quantity: 80,
    status: true,
    attribute: {
      'chất liệu': 'cotton jacquard',
      form: 'regular',
      màu: 'black',
      'phong cách': 'originals',
    },
  },
  {
    product_id: 1,
    size_id: 3,
    sku: 'ADI-AJJ-M-BLK-L',
    barcode: '10000002',
    base_price: 900000,
    quantity: 65,
    status: true,
    attribute: {
      'chất liệu': 'cotton jacquard',
      form: 'regular',
      màu: 'black',
      'phong cách': 'originals',
    },
  },

  // 2) Originals Twistknit Trefoil Polo Shirt (Men) – tops: S/M/L/XL
  {
    product_id: 2,
    size_id: 1,
    sku: 'ADI-OTTP-M-WHT-S',
    barcode: '10000003',
    base_price: 1200000,
    quantity: 10,
    status: true,
    attribute: { 'chất liệu': 'cotton pique', 'kiểu dáng': 'thanh lịch', màu: 'white' },
  },
  {
    product_id: 2,
    size_id: 2,
    sku: 'ADI-OTTP-M-WHT-M',
    barcode: '10000004',
    base_price: 1200000,
    quantity: 20,
    status: true,
    attribute: { 'chất liệu': 'cotton pique', 'kiểu dáng': 'thanh lịch', màu: 'white' },
  },
  {
    product_id: 2,
    size_id: 3,
    sku: 'ADI-OTTP-M-WHT-L',
    barcode: '10000005',
    base_price: 1200000,
    quantity: 30,
    status: true,
    attribute: { 'chất liệu': 'cotton pique', 'kiểu dáng': 'thanh lịch', màu: 'white' },
  },
  {
    product_id: 2,
    size_id: 4,
    sku: 'ADI-OTTP-M-WHT-XL',
    barcode: '10000006',
    base_price: 1200000,
    quantity: 15,
    status: true,
    attribute: { 'chất liệu': 'cotton pique', 'kiểu dáng': 'thanh lịch', màu: 'white' },
  },

  // 3) Twistweave Pinstripe Ankle Pants (Men) – pants: S/M/L
  {
    product_id: 3,
    size_id: 1,
    sku: 'ADI-TPAP-M-BLK-S',
    barcode: '10000007',
    base_price: 1300000,
    quantity: 22,
    status: true,
    attribute: {
      'chất liệu': 'poly-viscose',
      'họa tiết': 'pinstripe',
      phom: 'ankle',
      màu: 'black',
    },
  },
  {
    product_id: 3,
    size_id: 2,
    sku: 'ADI-TPAP-M-BLK-M',
    barcode: '10000008',
    base_price: 1300000,
    quantity: 26,
    status: true,
    attribute: {
      'chất liệu': 'poly-viscose',
      'họa tiết': 'pinstripe',
      phom: 'ankle',
      màu: 'black',
    },
  },
  {
    product_id: 3,
    size_id: 3,
    sku: 'ADI-TPAP-M-BLK-L',
    barcode: '10000009',
    base_price: 1300000,
    quantity: 18,
    status: true,
    attribute: {
      'chất liệu': 'poly-viscose',
      'họa tiết': 'pinstripe',
      phom: 'ankle',
      màu: 'black',
    },
  },

  // 4) Z.N.E. Shorts (Men) – shorts: S/M/L/XL
  {
    product_id: 4,
    size_id: 1,
    sku: 'ADI-ZNES-M-BLK-S',
    barcode: '10000010',
    base_price: 1250000,
    quantity: 25,
    status: true,
    attribute: { 'chất liệu': 'doubleknit', 'phong cách': 'athleisure', màu: 'black' },
  },
  {
    product_id: 4,
    size_id: 2,
    sku: 'ADI-ZNES-M-BLK-M',
    barcode: '10000011',
    base_price: 1250000,
    quantity: 28,
    status: true,
    attribute: { 'chất liệu': 'doubleknit', 'phong cách': 'athleisure', màu: 'black' },
  },
  {
    product_id: 4,
    size_id: 3,
    sku: 'ADI-ZNES-M-BLK-L',
    barcode: '10000012',
    base_price: 1250000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'doubleknit', 'phong cách': 'athleisure', màu: 'black' },
  },
  {
    product_id: 4,
    size_id: 4,
    sku: 'ADI-ZNES-M-BLK-XL',
    barcode: '10000013',
    base_price: 1250000,
    quantity: 12,
    status: true,
    attribute: { 'chất liệu': 'doubleknit', 'phong cách': 'athleisure', màu: 'black' },
  },

  // 5) Essentials 3-Stripes Cotton Tee (Women) – tops: S/M/L
  {
    product_id: 5,
    size_id: 28,
    sku: 'ADI-E3ST-W-BLK-S',
    barcode: '10000014',
    base_price: 790000,
    quantity: 40,
    status: true,
    attribute: { 'chất liệu': 'cotton', 'họa tiết': '3-stripes', form: 'regular', màu: 'black' },
  },
  {
    product_id: 5,
    size_id: 29,
    sku: 'ADI-E3ST-W-BLK-M',
    barcode: '10000015',
    base_price: 790000,
    quantity: 35,
    status: true,
    attribute: { 'chất liệu': 'cotton', 'họa tiết': '3-stripes', form: 'regular', màu: 'black' },
  },
  {
    product_id: 5,
    size_id: 30,
    sku: 'ADI-E3ST-W-BLK-L',
    barcode: '10000016',
    base_price: 790000,
    quantity: 20,
    status: true,
    attribute: { 'chất liệu': 'cotton', 'họa tiết': '3-stripes', form: 'regular', màu: 'black' },
  },

  // 6) Essentials Small Logo Cotton Lifestyle Tank Top (Women) – tops: S/M/L
  {
    product_id: 6,
    size_id: 28,
    sku: 'ADI-ESLT-W-WHT-S',
    barcode: '10000017',
    base_price: 690000,
    quantity: 30,
    status: true,
    attribute: { 'chất liệu': 'cotton', logo: 'small', kiểu: 'tank', màu: 'white' },
  },
  {
    product_id: 6,
    size_id: 29,
    sku: 'ADI-ESLT-W-WHT-M',
    barcode: '10000018',
    base_price: 690000,
    quantity: 28,
    status: true,
    attribute: { 'chất liệu': 'cotton', logo: 'small', kiểu: 'tank', màu: 'white' },
  },
  {
    product_id: 6,
    size_id: 30,
    sku: 'ADI-ESLT-W-WHT-L',
    barcode: '10000019',
    base_price: 690000,
    quantity: 24,
    status: true,
    attribute: { 'chất liệu': 'cotton', logo: 'small', kiểu: 'tank', màu: 'white' },
  },

  // 7) Adidas All Me Rib 7/8 Leggings (Women) – leggings: S/M/L
  {
    product_id: 7,
    size_id: 28,
    sku: 'ADI-AMR7-W-PRP-S',
    barcode: '10000020',
    base_price: 990000,
    quantity: 26,
    status: true,
    attribute: { 'chất liệu': 'rib knit', 'độ dài': '7/8', 'co giãn': 'tốt', màu: 'purple' },
  },
  {
    product_id: 7,
    size_id: 29,
    sku: 'ADI-AMR7-W-PRP-M',
    barcode: '10000021',
    base_price: 990000,
    quantity: 22,
    status: true,
    attribute: { 'chất liệu': 'rib knit', 'độ dài': '7/8', 'co giãn': 'tốt', màu: 'purple' },
  },
  {
    product_id: 7,
    size_id: 30,
    sku: 'ADI-AMR7-W-PRP-L',
    barcode: '10000022',
    base_price: 990000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'rib knit', 'độ dài': '7/8', 'co giãn': 'tốt', màu: 'purple' },
  },

  // 8) Adidas Originals GFX Skirt (Women) – skirt: S/M/L
  {
    product_id: 8,
    size_id: 32,
    sku: 'ADI-OGFX-W-BLU-S',
    barcode: '10000023',
    base_price: 850000,
    quantity: 20,
    status: true,
    attribute: { 'chất liệu': 'poly-cotton', 'họa tiết': 'graphic', màu: 'blue' },
  },
  {
    product_id: 8,
    size_id: 33,
    sku: 'ADI-OGFX-W-BLU-M',
    barcode: '10000024',
    base_price: 850000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'poly-cotton', 'họa tiết': 'graphic', màu: 'blue' },
  },
  {
    product_id: 8,
    size_id: 34,
    sku: 'ADI-OGFX-W-BLU-L',
    barcode: '10000025',
    base_price: 850000,
    quantity: 14,
    status: true,
    attribute: { 'chất liệu': 'poly-cotton', 'họa tiết': 'graphic', màu: 'blue' },
  },

  // ====================== NIKE (brand_id: 2) ======================
  // 9) Nike Dri-FIT Running T-Shirt (Men) – tops: S/M/L
  {
    product_id: 9,
    size_id: 10,
    sku: 'NIK-DFRT-M-BLK-S',
    barcode: '10000026',
    base_price: 819000,
    quantity: 50,
    status: true,
    attribute: {
      'chất liệu': 'polyester',
      'công nghệ': 'Dri-FIT',
      màu: 'black',
      'phong cách': 'running',
    },
  },
  {
    product_id: 9,
    size_id: 11,
    sku: 'NIK-DFRT-M-BLK-M',
    barcode: '10000027',
    base_price: 819000,
    quantity: 60,
    status: true,
    attribute: {
      'chất liệu': 'polyester',
      'công nghệ': 'Dri-FIT',
      màu: 'black',
      'phong cách': 'running',
    },
  },
  {
    product_id: 9,
    size_id: 12,
    sku: 'NIK-DFRT-M-BLK-L',
    barcode: '10000028',
    base_price: 819000,
    quantity: 55,
    status: true,
    attribute: {
      'chất liệu': 'polyester',
      'công nghệ': 'Dri-FIT',
      màu: 'black',
      'phong cách': 'running',
    },
  },

  // 10) Nike Heavyweight Polo (Men) – tops: S/M/L/XL
  {
    product_id: 10,
    size_id: 10,
    sku: 'NIK-HWPO-M-DRED-S',
    barcode: '10000029',
    base_price: 1299000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'heavy cotton', form: 'relaxed', màu: 'dark red' },
  },
  {
    product_id: 10,
    size_id: 11,
    sku: 'NIK-HWPO-M-DRED-M',
    barcode: '10000030',
    base_price: 1299000,
    quantity: 20,
    status: true,
    attribute: { 'chất liệu': 'heavy cotton', form: 'relaxed', màu: 'dark red' },
  },
  {
    product_id: 10,
    size_id: 12,
    sku: 'NIK-HWPO-M-DRED-L',
    barcode: '10000031',
    base_price: 1299000,
    quantity: 16,
    status: true,
    attribute: { 'chất liệu': 'heavy cotton', form: 'relaxed', màu: 'dark red' },
  },
  {
    product_id: 10,
    size_id: 13,
    sku: 'NIK-HWPO-M-DRED-XL',
    barcode: '10000032',
    base_price: 1299000,
    quantity: 12,
    status: true,
    attribute: { 'chất liệu': 'heavy cotton', form: 'relaxed', màu: 'dark red' },
  },

  // 11) Nike Stride Repel UV Running Jacket (Men) – outer: S/M/L
  {
    product_id: 11,
    size_id: 10,
    sku: 'NIK-SRUV-M-WHT-S',
    barcode: '10000033',
    base_price: 2599000,
    quantity: 14,
    status: true,
    attribute: { 'chất liệu': 'poly woven', 'tính năng': 'UV repel', màu: 'white' },
  },
  {
    product_id: 11,
    size_id: 11,
    sku: 'NIK-SRUV-M-WHT-M',
    barcode: '10000034',
    base_price: 2599000,
    quantity: 16,
    status: true,
    attribute: { 'chất liệu': 'poly woven', 'tính năng': 'UV repel', màu: 'white' },
  },
  {
    product_id: 11,
    size_id: 12,
    sku: 'NIK-SRUV-M-WHT-L',
    barcode: '10000035',
    base_price: 2599000,
    quantity: 12,
    status: true,
    attribute: { 'chất liệu': 'poly woven', 'tính năng': 'UV repel', màu: 'white' },
  },

  // 12) Nike Dri-FIT Victory Golf Trousers (Men) – pants: S/M/L/XL
  {
    product_id: 12,
    size_id: 14,
    sku: 'NIK-VGTR-M-BLK-S',
    barcode: '10000036',
    base_price: 2759000,
    quantity: 14,
    status: true,
    attribute: {
      'chất liệu': 'poly-spandex',
      'công nghệ': 'Dri-FIT',
      màu: 'black',
      'phong cách': 'golf',
    },
  },
  {
    product_id: 12,
    size_id: 15,
    sku: 'NIK-VGTR-M-BLK-M',
    barcode: '10000037',
    base_price: 2759000,
    quantity: 16,
    status: true,
    attribute: {
      'chất liệu': 'poly-spandex',
      'công nghệ': 'Dri-FIT',
      màu: 'black',
      'phong cách': 'golf',
    },
  },
  {
    product_id: 12,
    size_id: 16,
    sku: 'NIK-VGTR-M-BLK-L',
    barcode: '10000038',
    base_price: 2759000,
    quantity: 10,
    status: true,
    attribute: {
      'chất liệu': 'poly-spandex',
      'công nghệ': 'Dri-FIT',
      màu: 'black',
      'phong cách': 'golf',
    },
  },
  {
    product_id: 12,
    size_id: 17,
    sku: 'NIK-VGTR-M-BLK-XL',
    barcode: '10000039',
    base_price: 2759000,
    quantity: 8,
    status: true,
    attribute: {
      'chất liệu': 'poly-spandex',
      'công nghệ': 'Dri-FIT',
      màu: 'black',
      'phong cách': 'golf',
    },
  },

  // 13) Nike Dri-FIT Challenger Brief-Lined Versatile Shorts (Men) – shorts: S/M/L
  {
    product_id: 13,
    size_id: 14,
    sku: 'NIK-DCBL-M-GRAY-S',
    barcode: '10000040',
    base_price: 999000,
    quantity: 22,
    status: true,
    attribute: { 'chất liệu': 'poly', lót: 'brief', màu: 'gray' },
  },
  {
    product_id: 13,
    size_id: 15,
    sku: 'NIK-DCBL-M-GRAY-M',
    barcode: '10000041',
    base_price: 999000,
    quantity: 26,
    status: true,
    attribute: { 'chất liệu': 'poly', lót: 'brief', màu: 'gray' },
  },
  {
    product_id: 13,
    size_id: 16,
    sku: 'NIK-DCBL-M-GRAY-L',
    barcode: '10000042',
    base_price: 999000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'poly', lót: 'brief', màu: 'gray' },
  },

  // 14) Just Do It: Nike Basketball T-Shirt (Women) – tops: S/M/L
  {
    product_id: 14,
    size_id: 36,
    sku: 'NIK-JDBT-W-BLK-S',
    barcode: '10000043',
    base_price: 749000,
    quantity: 40,
    status: true,
    attribute: { 'chất liệu': 'cotton', graphic: 'Just Do It Basketball', màu: 'black' },
  },
  {
    product_id: 14,
    size_id: 37,
    sku: 'NIK-JDBT-W-BLK-M',
    barcode: '10000044',
    base_price: 749000,
    quantity: 36,
    status: true,
    attribute: { 'chất liệu': 'cotton', graphic: 'Just Do It Basketball', màu: 'black' },
  },
  {
    product_id: 14,
    size_id: 38,
    sku: 'NIK-JDBT-W-BLK-L',
    barcode: '10000045',
    base_price: 749000,
    quantity: 28,
    status: true,
    attribute: { 'chất liệu': 'cotton', graphic: 'Just Do It Basketball', màu: 'black' },
  },

  // 15) Nike Sportswear Windrunner Jacket (Women) – outer: S/M/L
  {
    product_id: 15,
    size_id: 36,
    sku: 'NIK-WIND-W-BLK-S',
    barcode: '10000046',
    base_price: 2599000,
    quantity: 16,
    status: true,
    attribute: { 'chất liệu': 'woven', 'thiết kế': 'Windrunner', màu: 'black' },
  },
  {
    product_id: 15,
    size_id: 37,
    sku: 'NIK-WIND-W-BLK-M',
    barcode: '10000047',
    base_price: 2599000,
    quantity: 14,
    status: true,
    attribute: { 'chất liệu': 'woven', 'thiết kế': 'Windrunner', màu: 'black' },
  },
  {
    product_id: 15,
    size_id: 38,
    sku: 'NIK-WIND-W-BLK-L',
    barcode: '10000048',
    base_price: 2599000,
    quantity: 12,
    status: true,
    attribute: { 'chất liệu': 'woven', 'thiết kế': 'Windrunner', màu: 'black' },
  },

  // 16) NikeCourt Advantage Dri-FIT Skirt (Women) – skirt: S/M/L
  {
    product_id: 16,
    size_id: 41,
    sku: 'NIK-NCAD-W-BLU-S',
    barcode: '10000049',
    base_price: 1399000,
    quantity: 20,
    status: true,
    attribute: { 'chất liệu': 'poly-spandex', 'công nghệ': 'Dri-FIT', màu: 'blue' },
  },
  {
    product_id: 16,
    size_id: 42,
    sku: 'NIK-NCAD-W-BLU-M',
    barcode: '10000050',
    base_price: 1399000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'poly-spandex', 'công nghệ': 'Dri-FIT', màu: 'blue' },
  },
  {
    product_id: 16,
    size_id: 43,
    sku: 'NIK-NCAD-W-BLU-L',
    barcode: '10000051',
    base_price: 1399000,
    quantity: 16,
    status: true,
    attribute: { 'chất liệu': 'poly-spandex', 'công nghệ': 'Dri-FIT', màu: 'blue' },
  },

  // 17) Nike High-Waisted Loose Wide-Leg Trousers (Women) – pants: S/M/L
  {
    product_id: 17,
    size_id: 41,
    sku: 'NIK-HWLW-W-BLK-S',
    barcode: '10000052',
    base_price: 2199000,
    quantity: 16,
    status: true,
    attribute: { 'chất liệu': 'polyester', phom: 'wide-leg, high-waist', màu: 'black' },
  },
  {
    product_id: 17,
    size_id: 42,
    sku: 'NIK-HWLW-W-BLK-M',
    barcode: '10000053',
    base_price: 2199000,
    quantity: 14,
    status: true,
    attribute: { 'chất liệu': 'polyester', phom: 'wide-leg, high-waist', màu: 'black' },
  },
  {
    product_id: 17,
    size_id: 43,
    sku: 'NIK-HWLW-W-BLK-L',
    barcode: '10000054',
    base_price: 2199000,
    quantity: 12,
    status: true,
    attribute: { 'chất liệu': 'polyester', phom: 'wide-leg, high-waist', màu: 'black' },
  },

  // ====================== UNIQLO (brand_id: 3) ======================
  // 18) UNIQLO Áo Thun Milano Vải Gân (Men) – tops: S/M/L
  {
    product_id: 18,
    size_id: 19,
    sku: 'UQL-MILN-M-BEI-S',
    barcode: '10000055',
    base_price: 399000,
    quantity: 60,
    status: true,
    attribute: { 'chất liệu': 'milano rib', form: 'regular', màu: 'beige' },
  },
  {
    product_id: 18,
    size_id: 20,
    sku: 'UQL-MILN-M-BEI-M',
    barcode: '10000056',
    base_price: 399000,
    quantity: 54,
    status: true,
    attribute: { 'chất liệu': 'milano rib', form: 'regular', màu: 'beige' },
  },
  {
    product_id: 18,
    size_id: 21,
    sku: 'UQL-MILN-M-BEI-L',
    barcode: '10000057',
    base_price: 399000,
    quantity: 48,
    status: true,
    attribute: { 'chất liệu': 'milano rib', form: 'regular', màu: 'beige' },
  },

  // 19) UNIQLO Áo Sơ Mi Vải Dạ | Caro (Men) – shirts: S/M/L/XL
  {
    product_id: 19,
    size_id: 19,
    sku: 'UQL-FLNL-M-RED-S',
    barcode: '10000058',
    base_price: 599000,
    quantity: 24,
    status: true,
    attribute: { 'chất liệu': 'flannel', 'họa tiết': 'caro', màu: 'red' },
  },
  {
    product_id: 19,
    size_id: 20,
    sku: 'UQL-FLNL-M-RED-M',
    barcode: '10000059',
    base_price: 599000,
    quantity: 22,
    status: true,
    attribute: { 'chất liệu': 'flannel', 'họa tiết': 'caro', màu: 'red' },
  },
  {
    product_id: 19,
    size_id: 21,
    sku: 'UQL-FLNL-M-RED-L',
    barcode: '10000060',
    base_price: 599000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'flannel', 'họa tiết': 'caro', màu: 'red' },
  },
  {
    product_id: 19,
    size_id: 22,
    sku: 'UQL-FLNL-M-RED-XL',
    barcode: '10000061',
    base_price: 599000,
    quantity: 12,
    status: true,
    attribute: { 'chất liệu': 'flannel', 'họa tiết': 'caro', màu: 'red' },
  },

  // 20) UNIQLO Quần Jeans Dáng Rộng Ống Suông (Men) – jeans: S/M/L
  {
    product_id: 20,
    size_id: 24,
    sku: 'UQL-JNSW-M-BLK-S',
    barcode: '10000062',
    base_price: 799000,
    quantity: 22,
    status: true,
    attribute: { 'chất liệu': 'denim', phom: 'wide straight', màu: 'black' },
  },
  {
    product_id: 20,
    size_id: 25,
    sku: 'UQL-JNSW-M-BLK-M',
    barcode: '10000063',
    base_price: 799000,
    quantity: 26,
    status: true,
    attribute: { 'chất liệu': 'denim', phom: 'wide straight', màu: 'black' },
  },
  {
    product_id: 20,
    size_id: 26,
    sku: 'UQL-JNSW-M-BLK-L',
    barcode: '10000064',
    base_price: 799000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'denim', phom: 'wide straight', màu: 'black' },
  },

  // 21) UNIQLO Quần Short Vải Jersey (Men) – shorts: S/M/L
  {
    product_id: 21,
    size_id: 24,
    sku: 'UQL-JERS-M-BRW-S',
    barcode: '10000065',
    base_price: 399000,
    quantity: 40,
    status: true,
    attribute: { 'chất liệu': 'jersey', form: 'regular', màu: 'brown' },
  },
  {
    product_id: 21,
    size_id: 25,
    sku: 'UQL-JERS-M-BRW-M',
    barcode: '10000066',
    base_price: 399000,
    quantity: 36,
    status: true,
    attribute: { 'chất liệu': 'jersey', form: 'regular', màu: 'brown' },
  },
  {
    product_id: 21,
    size_id: 26,
    sku: 'UQL-JERS-M-BRW-L',
    barcode: '10000067',
    base_price: 399000,
    quantity: 28,
    status: true,
    attribute: { 'chất liệu': 'jersey', form: 'regular', màu: 'brown' },
  },

  // 22) UNIQLO Áo Thun AIRism Cotton (Women) – tops: S/M/L
  {
    product_id: 22,
    size_id: 45,
    sku: 'UQL-AIRM-W-BLK-S',
    barcode: '10000068',
    base_price: 299000,
    quantity: 70,
    status: true,
    attribute: { 'chất liệu': 'AIRism cotton', form: 'regular', màu: 'black' },
  },
  {
    product_id: 22,
    size_id: 46,
    sku: 'UQL-AIRM-W-BLK-M',
    barcode: '10000069',
    base_price: 299000,
    quantity: 64,
    status: true,
    attribute: { 'chất liệu': 'AIRism cotton', form: 'regular', màu: 'black' },
  },
  {
    product_id: 22,
    size_id: 47,
    sku: 'UQL-AIRM-W-BLK-L',
    barcode: '10000070',
    base_price: 299000,
    quantity: 58,
    status: true,
    attribute: { 'chất liệu': 'AIRism cotton', form: 'regular', màu: 'black' },
  },

  // 23) UNIQLO Áo Hoodie Nỉ Dry Kéo Khóa (Women) – outer: S/M/L
  {
    product_id: 23,
    size_id: 45,
    sku: 'UQL-DRYH-W-NAVY-S',
    barcode: '10000071',
    base_price: 699000,
    quantity: 24,
    status: true,
    attribute: { 'chất liệu': 'french terry', 'tính năng': 'DRY', màu: 'navy' },
  },
  {
    product_id: 23,
    size_id: 46,
    sku: 'UQL-DRYH-W-NAVY-M',
    barcode: '10000072',
    base_price: 699000,
    quantity: 22,
    status: true,
    attribute: { 'chất liệu': 'french terry', 'tính năng': 'DRY', màu: 'navy' },
  },
  {
    product_id: 23,
    size_id: 47,
    sku: 'UQL-DRYH-W-NAVY-L',
    barcode: '10000073',
    base_price: 699000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'french terry', 'tính năng': 'DRY', màu: 'navy' },
  },

  // 24) UNIQLO Quần Jeans Ống Loe Rộng Dáng Rũ (Women) – jeans: S/M/L
  {
    product_id: 24,
    size_id: 50,
    sku: 'UQL-JNFL-W-BLU-S',
    barcode: '10000074',
    base_price: 899000,
    quantity: 20,
    status: true,
    attribute: { 'chất liệu': 'denim', phom: 'flare wide', màu: 'blue' },
  },
  {
    product_id: 24,
    size_id: 51,
    sku: 'UQL-JNFL-W-BLU-M',
    barcode: '10000075',
    base_price: 899000,
    quantity: 18,
    status: true,
    attribute: { 'chất liệu': 'denim', phom: 'flare wide', màu: 'blue' },
  },
  {
    product_id: 24,
    size_id: 52,
    sku: 'UQL-JNFL-W-BLU-L',
    barcode: '10000076',
    base_price: 899000,
    quantity: 16,
    status: true,
    attribute: { 'chất liệu': 'denim', phom: 'flare wide', màu: 'blue' },
  },

  // 25) UNIQLO Quần Easy Shorts Vải Cotton | Hickory (Women) – shorts: S/M/L
  {
    product_id: 25,
    size_id: 50,
    sku: 'UQL-EZSH-W-PNK-S',
    barcode: '10000077',
    base_price: 399000,
    quantity: 32,
    status: true,
    attribute: { 'chất liệu': 'cotton hickory', form: 'easy shorts', màu: 'pink' },
  },
  {
    product_id: 25,
    size_id: 51,
    sku: 'UQL-EZSH-W-PNK-M',
    barcode: '10000078',
    base_price: 399000,
    quantity: 28,
    status: true,
    attribute: { 'chất liệu': 'cotton hickory', form: 'easy shorts', màu: 'pink' },
  },
  {
    product_id: 25,
    size_id: 52,
    sku: 'UQL-EZSH-W-PNK-L',
    barcode: '10000079',
    base_price: 399000,
    quantity: 24,
    status: true,
    attribute: { 'chất liệu': 'cotton hickory', form: 'easy shorts', màu: 'pink' },
  },
];

// ===== HÀM ĐẨY LÊN DB (idempotent theo SKU) =====
export async function seedVariantsManualFull(prisma: PrismaClient) {
  console.log(`🏷️  Upsert ${variantsData.length} product_variants (manual full)`);

  for (const row of variantsData) {
    await prisma.product_variants.upsert({
      where: { sku: row.sku },
      update: {
        base_price: row.base_price,
        quantity: row.quantity,
        status: row.status,
        attribute: row.attribute,
        barcode: row.barcode,
        size_id: row.size_id, // để null (bạn sửa tay khi biết ID)
        product_id: row.product_id, // bạn sửa tay nếu product_id khác
      },
      create: {
        product_id: row.product_id,
        size_id: row.size_id, // để null
        sku: row.sku,
        barcode: row.barcode,
        base_price: row.base_price,
        quantity: row.quantity,
        status: row.status,
        attribute: row.attribute,
      },
    });
  }

  console.log('✅ Done manual full variants.');
}

// seedVariantsManualFull().finally(() => prisma.$disconnect());
